name: Build e4990a executables

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -Ur requirements.txt
        python -m pip install -Ur requirements-dev.txt
    - name: Create README
      if: matrix.os == 'macos-latest'
      run: |
        python -m markdown -x extra README.md > README.html
    - name: Build executable (macos)
      if: matrix.os == 'macos-latest'
      run: |
        ./build_installer.sh
    - name: Build executable (windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        .\build_installer.bat
    - name: Create distributable
      run: |
        ./create_release.sh
    - uses: actions/upload-artifact@v2
      with:
        name: e4990a
        path: dist/*
